# Generated by Django 5.0.2 on 2024-02-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_added_by_book_created_at_book_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=None, upload_to='uploads/books/%Y/%m/%d/'),
        ),
    ]
